---
config:
  layout: elk
  elk:
    mergeEdges: false
    nodePlacementStrategy: LINEAR_SEGMENTS
---
classDiagram
    User
    Senior
    Tutor
  
    Activity
    ActivityBoard
    TutorBoard
    ActivityManager
    Queue~Senior~

    ChatTab
    ConversationView
    ConversationManager
    ChatDatabase
    CommunicationManager


    %% Senior e Tutor HERDAM de User.
    User <|-- Senior
    User <|-- Tutor

    %% Senior e Tutor possuem ambos uma relação de ASSOCIAÇÃO mútua
    %% com Activity.
    Senior "0..N" <--> "0..N" Activity
    Tutor "0..N" <--> "1" Activity

    %% Tanto ActivityBoard quanto ActivityManager possuem uma relação
    %% de DEPENDÊNCIA com as classes Senior e Activity, porque nenhuma
    %% delas guarda uma referência permanente a estes objetos, apenas
    %% necessita pontualmente deles.
    ActivityBoard ..> Senior
    ActivityManager ..> Senior
    ActivityBoard ..> Activity
    ActivityManager ..> Activity

    %% ActivityBoard possui uma relação de ASSOCIAÇÃO com ActivityManager,
    %% pois não gerencia o tempo de vida de ActivityManager, mas sabe de
    %% sua existência e delega as requisições de negócio para ele.
    ActivityBoard "1..N" --> "1" ActivityManager

    %% ActivityManager possui uma relação de COMPOSIÇÃO com Queue,
    %% pois, se ActivityManager for destruído, Queue também é.
    ActivityManager "1" *-- "0..N" Queue~Senior~

    class User {
      -name: str
      -age: int
      -email_address: str
      -cellphone_number: str
    }

    class Senior {
      -enrolled: list[Activity]
    }

    class Tutor {
      -assigned: list[Activity]
    }

    class Activity {
      -name: str
      -total_spots: int
      -remaining_spots: int
      -participants: list[Senior]
      -tutor: Tutor
    }

    note for ActivityBoard "O atributo 'new_activity' existe apenas se 'user' for uma instância de 'Tutor'."
    class ActivityBoard {
      -activity_manager: ActivityManager
      -user: User
      -selected_activity: Activity | None
      -new_activity: Activity | None

      +show() None
      +hide() None
      +get_available_activities() list[Activity]
      +handle_show_available_activities_click() None
      +handle_enroll_click() bool
      +handle_enter_queue_click() bool
      +handle_register_new_activity_click() None
      +handle_confirm_register_new_activity_click() bool

      -display_error_message(message: str) None
      -display_new_activity_form() None
    }

    class ActivityManager {
      -queue_map: dict[Activity, Queue[Senior]]

      +get_available_activities() list[Activity]
      +enroll(senior: Senior, activity: Activity) bool
      +add_to_queue(senior: Senior, activity: Activity) bool
      +register_new_activity(tutor: Tutor, activity: Activity) bool
    }

    class Queue~Senior~ {
      +init() None
      +push(element: Senior) None
      +pop(element: Senior) None
      +is_empty() bool
      +is_full() bool
      +destroy() None
    }
